name: Build Angular App

on:
  push:
    branches: [ main ]
jobs:
  build-angular:
    runs-on: ubuntu-lagtest

    steps:
      - uses: actions/checkout@4

      - name: Setup Node JS
        uses: action/setup-node@4
        with:
          node-version: 18.x
      
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist

  deploy-angular:
    runs-on: ubuntu-lagtest
    needs: build-angular

    steps:
      - name: Test
        run: echo "test step"
    