name: Build Angular App

on:
  push:
    branches: [ main ]
jobs:
  build-angular:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@4

      - name: Setup Node JS
        uses: action/setup-node@4
        with:
          node-version: 18.x
      
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist

  job2:
    runs-on: ubuntu-latest

    steps:
      - name: Test1
        run: echo "test1 step"

  deploy-angular:
    runs-on: ubuntu-latest
    if: ${{ always() }} # This will run even if the previous jobs fail
    needs: [ build-angular, job2 ]
'''
    # or this can also be written as below:
    needs:
      - build-angular
      - job2
'''
    steps:
      - name: Test
        run: echo "test step"